name: Run Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable-tests.yml
    with:
      node-versions: '["lts/*", "latest"]'

  # Add a job to save the workflow files as artifacts
  save-workflows:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Upload workflow files
        uses: actions/upload-artifact@v4
        with:
          name: workflow-files
          path: .github/workflows/*.yml
          retention-days: 90
